OAS/Controllers/Common/AreaController.cs
using DBFactoryEntity;
using OAS.Bll;
using OAS.Model.Common;
using OAS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OAS.Controllers.Common
{
    public class AreaController : BaseController
    {
        public ActionResult Index()
        {
            ModuleNo = "AreaList";
            ViewBag.ToolBar = BuildPowerButtons();
            return View();
        }

        [HttpPost]
        public JsonResult Index(string areano, string areaname)
        {
            CommonBll commbll = new CommonBll();
            OperateResultModel orm = commbll.QueryAreaInfos(areano, areaname);
            return JsonResultHelper.ConvertToJsonResult(orm);
        }

        public PartialViewResult Edit(string areano)
        {
            CommonBll commbll = new CommonBll();
            tbl_areainfo model = null;
            if (!string.IsNullOrEmpty(areano))
            {
                model = commbll.QueryAreaInfo(areano);
            }
            return PartialView(model);
        }

        [HttpPost]
        public JsonResult Add(tbl_areainfo model)
        {
            model.creater = SessionUser.UserNo;
            model.createdate = DateTime.Now;
            model.editer = model.creater;
            model.editdate = model.createdate;
            CommonBll commbll = new CommonBll();
            OperateResultModel orm = commbll.InsertAreaInfo(model);
            return JsonResultHelper.ConvertToJsonResult(orm);
        }

        [HttpPost]
        public JsonResult Update(tbl_areainfo model)
        {
            model.editer = SessionUser.UserNo;
            model.editdate = DateTime.Now;
            CommonBll commbll = new CommonBll();
            OperateResultModel orm = commbll.UpdateAreaInfo(model);
            return JsonResultHelper.ConvertToJsonResult(orm);
        }

        [HttpPost]
        public JsonResult Delete(string areano)
        {
            CommonBll commbll = new CommonBll();
            OperateResultModel orm = commbll.DeleteAreaInfo(areano);
            return JsonResultHelper.ConvertToJsonResult(orm);
        }

        public PartialViewResult Select(string id, string name, string classname, string value)
        {
            if (!string.IsNullOrEmpty(id))
            {
                ViewBag.ID = id;
            }
            if (!string.IsNullOrEmpty(name))
            {
                ViewBag.Name = name;
            }
            if (!string.IsNullOrEmpty(classname))
            {
                ViewBag.ClassName = classname;
            }
            ViewBag.Value = value;

            CommonBll commbll = new CommonBll();
            OperateResultModel orm = commbll.QueryAreaInfos("", "");
            return PartialView(orm.rows);
        }
    }
}

OAS/Controllers/Jiax/JiaolianController.cs
using DBFactoryEntity;
using OAS.Bll;
using OAS.Model.Jiax;
using OAS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OAS.Controllers.Jiax
{
    public class JiaolianController : BaseController
    {
        public ActionResult Index()
        {
            ModuleNo = "JiaxJiaolian";
            ViewBag.ToolBar = BuildPowerButtons();
            return View();
        }

        [HttpPost]
        public JsonResult Index(string jiaolh, string xingming, string shenfhm, int page = 1, int rows = 20)
        {
            PaginModel pm = new PaginModel()
            {
                page = page,
                pagesize = rows
            };
            JiaxInfo jiaxinfo = new JiaxInfo();
            OperateResultModel orm = jiaxinfo.QueryJiaolians(jiaolh, xingming, shenfhm, pm);
            return JsonResultHelper.ConvertToJsonResult(orm);
        }

        public PartialViewResult Edit(string jiaolh)
        {
            JiaxInfo jiaxinfo = new JiaxInfo();
            tbl_jiaolian model = null;
            if (!string.IsNullOrEmpty(jiaolh))
            {
                model = jiaxinfo.QueryJiaolian(jiaolh);
            }
            return PartialView(model);
        }

        [HttpPost]
        public JsonResult Add(tbl_jiaolian model)
        {
            model.creater = SessionUser.UserNo;
            model.createdate = DateTime.Now;
            model.editer = model.creater;
            model.editdate = model.createdate;
            JiaxInfo jiaxinfo = new JiaxInfo();
            OperateResultModel orm = jiaxinfo.InsertJiaolian(model);
            return JsonResultHelper.ConvertToJsonResult(orm);
        }

        [HttpPost]
        public JsonResult Update(tbl_jiaolian model)
        {
            model.editer = SessionUser.UserNo;
            model.editdate = DateTime.Now;
            JiaxInfo jiaxinfo = new JiaxInfo();
            OperateResultModel orm = jiaxinfo.UpdateJiaolian(model);
            return JsonResultHelper.ConvertToJsonResult(orm);
        }

        [HttpPost]
        public JsonResult Delete(string jiaolh)
        {
            JiaxInfo jiaxinfo = new JiaxInfo();
            OperateResultModel orm = jiaxinfo.DeleteJiaolian(jiaolh);
            return JsonResultHelper.ConvertToJsonResult(orm);
        }
    }
}

OAS/Controllers/Jiax/JiaxController.cs
using DBFactoryEntity;
using OAS.Bll;
using OAS.Model.Jiax;
using OAS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OAS.Controllers.Jiax
{
    public class JiaxController : BaseController
    {
        public ActionResult Index()
        {
            ModuleNo = "JiaxList";
            ViewBag.ToolBar = BuildPowerButtons();
            return View();
        }

        [HttpPost]
        public JsonResult Index(string jiaxname, string areano)
        {
            JiaxInfo jiaxinfo = new JiaxInfo();
            OperateResultModel orm = jiaxinfo.QueryJiaxes(jiaxname, areano);
            return JsonResultHelper.ConvertToJsonResult(orm);
        }

        public PartialViewResult Edit(string jiaxid)
        {
            JiaxInfo jiaxinfo = new JiaxInfo();
            tbl_jiax model = null;
            if (!string.IsNullOrEmpty(jiaxid))
            {
                model = jiaxinfo.QueryJiax(jiaxid);
            }
            return PartialView(model);
        }

        [HttpPost]
        public JsonResult Add(tbl_jiax model)
        {
            model.creater = SessionUser.UserNo;
            model.createdate = DateTime.Now;
            model.editer = model.creater;
            model.editdate = model.createdate;
            JiaxInfo jiaxinfo = new JiaxInfo();
            OperateResultModel orm = jiaxinfo.InsertJiax(model);
            return JsonResultHelper.ConvertToJsonResult(orm);
        }

        [HttpPost]
        public JsonResult Update(tbl_jiax model)
        {
            model.editer = SessionUser.UserNo;
            model.editdate = DateTime.Now;
            JiaxInfo jiaxinfo = new JiaxInfo();
            OperateResultModel orm = jiaxinfo.UpdateJiax(model);
            return JsonResultHelper.ConvertToJsonResult(orm);
        }

        [HttpPost]
        public JsonResult Delete(string jiaxid)
        {
            JiaxInfo jiaxinfo = new JiaxInfo();
            OperateResultModel orm = jiaxinfo.DeleteJiax(jiaxid);
            return JsonResultHelper.ConvertToJsonResult(orm);
        }

        public PartialViewResult Select(string id, string name, string classname, string value)
        {
            if (!string.IsNullOrEmpty(id))
            {
                ViewBag.ID = id;
            }
            if (!string.IsNullOrEmpty(name))
            {
                ViewBag.Name = name;
            }
            if (!string.IsNullOrEmpty(classname))
            {
                ViewBag.ClassName = classname;
            }
            ViewBag.Value = value;

            JiaxInfo jiaxinfo = new JiaxInfo();
            OperateResultModel orm = jiaxinfo.QueryJiaxes("", "");
            return PartialView(orm.rows);
        }
    }
}

OAS/Controllers/Jiax/TestRecordsController.cs
using DBFactoryEntity;
using OAS.Bll;
using OAS.Model.Study;
using OAS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OAS.Controllers.Jiax
{
    public class TestRecordsController : BaseController
    {
        public ActionResult Index()
        {
            ModuleNo = "StudyRecords";
            ViewBag.ToolBar = BuildPowerButtons();
            return View();
        }

        [HttpPost]
        public JsonResult Index(string xueyh, string xingming, int page = 1, int rows = 20)
        {
            PaginModel pm = new PaginModel()
            {
                page = page,
                pagesize = rows
            };
            Study study = new Study();
            OperateResultModel orm = study.QueryTestRecords(xueyh, xingming, pm);
            return JsonResultHelper.ConvertToJsonResult(orm);
        }

        //public PartialViewResult Edit(string testno)
        //{
        //    Study study = new Study();
        //    tbl_test_records model = null;
        //    if (!string.IsNullOrEmpty(testno))
        //    {
        //        model = study.QueryTestRecord(testno);
        //    }
        //    return PartialView(model);
        //}

        //[HttpPost]
        //public JsonResult Add(tbl_test_records model)
        //{
        //    model.creater = SessionUser.UserNo;
        //    model.createdate = DateTime.Now;
        //    Study study = new Study();
        //    OperateResultModel orm = study.InsertTestRecord(model);
        //    return JsonResultHelper.ConvertToJsonResult(orm);
        //}

        //[HttpPost]
        //public JsonResult Update(tbl_test_records model)
        //{
        //    Study study = new Study();
        //    OperateResultModel orm = study.UpdateTestRecord(model);
        //    return JsonResultHelper.ConvertToJsonResult(orm);
        //}
        //
        //[HttpPost]
        //public JsonResult Delete(string xueyh)
        //{
        //    Study study = new Study();
        //    OperateResultModel orm = study.DeleteTestRecord(xueyh);
        //    return JsonResultHelper.ConvertToJsonResult(orm);
        //}
    }
}

OAS/Controllers/Jiax/XueyuanController.cs
using DBFactoryEntity;
using OAS.Bll;
using OAS.Model.Jiax;
using OAS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OAS.Controllers.Jiax
{
    public class XueyuanController : BaseController
    {
        public ActionResult Index()
        {
            ModuleNo = "JiaxXueyuan";
            ViewBag.ToolBar = BuildPowerButtons();
            return View();
        }

        [HttpPost]
        public JsonResult Index(string xueyh, string xingming, string shenfhm, int page = 1, int rows = 20)
        {
            PaginModel pm = new PaginModel()
            {
                page = page,
                pagesize = rows
            };
            JiaxInfo jiaxinfo = new JiaxInfo();
            OperateResultModel orm = jiaxinfo.QueryXueyuans(xueyh, xingming, shenfhm, pm);
            return JsonResultHelper.ConvertToJsonResult(orm);
        }

        public PartialViewResult Edit(string xueyh)
        {
            JiaxInfo jiaxinfo = new JiaxInfo();
            tbl_xueyuan model = null;
            if (!string.IsNullOrEmpty(xueyh))
            {
                model = jiaxinfo.QueryXueyuan(xueyh);
            }
            return PartialView(model);
        }

        [HttpPost]
        public JsonResult Add(tbl_xueyuan model)
        {
            model.creater = SessionUser.UserNo;
            model.createdate = DateTime.Now;
            model.editer = model.creater;
            model.editdate = model.createdate;
            JiaxInfo jiaxinfo = new JiaxInfo();
            OperateResultModel orm = jiaxinfo.InsertXueyuan(model);
            return JsonResultHelper.ConvertToJsonResult(orm);
        }

        [HttpPost]
        public JsonResult Update(tbl_xueyuan model)
        {
            model.editer = SessionUser.UserNo;
            model.editdate = DateTime.Now;
            JiaxInfo jiaxinfo = new JiaxInfo();
            OperateResultModel orm = jiaxinfo.UpdateXueyuan(model);
            return JsonResultHelper.ConvertToJsonResult(orm);
        }

        [HttpPost]
        public JsonResult Delete(string xueyh)
        {
            JiaxInfo jiaxinfo = new JiaxInfo();
            OperateResultModel orm = jiaxinfo.DeleteXueyuan(xueyh);
            return JsonResultHelper.ConvertToJsonResult(orm);
        }
    }
}

OAS/Views/Jiax/Edit.cshtml
@model OAS.Model.Jiax.tbl_jiax
@{
    Layout = null;
}

@using (Ajax.BeginForm(Model == null ? "Add" : "Update",
    new { },
    new AjaxOptions()
    {
        OnBegin = "showLayout",
        OnComplete = "hideLayout",
        OnSuccess = "showUpdateResult"
    },
        new { id = "editform" }))
{
    <table class="ui-table">
        <tr>
            <td class="label">驾校ID：</td>
            <td class="value">
                <input type="text" name="jiaxid" class="form-textbox" @(Model == null ? "" : "readonly") value="@(Model == null ? "" : Model.jiaxid)" />
            </td>
        </tr>
        <tr>
            <td class="label">驾校名称：</td>
            <td class="value">
                <input type="text" name="jiaxname" class="form-textbox" value="@(Model == null ? "" : Model.jiaxname)" />
            </td>
        </tr>
        <tr>
            <td class="label">区域：</td>
            <td class="value">
                @Html.Action("Select", "Area", new { name = "areano", id = "areano", classname = "form-textbox easyui-combobox", value = Model == null ? "" : Model.areano })
                <input type="hidden" name="areaname" id="areaname" value="@(Model == null ? "" : Model.areaname)" />
            </td>
        </tr>
        <tr>
            <td class="label">驾校联系人：</td>
            <td class="value">
                <input type="text" name="jiaxcontacter" class="form-textbox" value="@(Model == null ? "" : Model.jiaxcontacter)" />
            </td>
        </tr>
        <tr>
            <td class="label">固定电话：</td>
            <td class="value">
                <input type="text" name="jiaxtel" class="form-textbox" value="@(Model == null ? "" : Model.jiaxtel)" />
            </td>
        </tr>
        <tr>
            <td class="label">手机：</td>
            <td class="value">
                <input type="text" name="jiaxmobile" class="form-textbox" value="@(Model == null ? "" : Model.jiaxmobile)" />
            </td>
        </tr>
        <tr>
            <td class="label">联系地址：</td>
            <td class="value">
                <input type="text" name="jiaxaddress" class="form-textbox" value="@(Model == null ? "" : Model.jiaxaddress)" />
            </td>
        </tr>
    </table>
}

OAS/Views/Jiax/Index.cshtml
@{
    ViewBag.Title = "驾校管理";
}
<div data-options="region:'north',border:false" style="height:93px;">
    <div class="queryframe">
        <table>
            <tr>
                <td>驾校名称：</td>
                <td>
                    <input type="text" name="userno" id="userno" class="textbox ui-box" />
                </td>
                <td>区域：</td>
                <td>
                    @Html.Action("Select", "Area", new { name = "ddlareano", id = "ddlareano", classname = "textbox easyui-combobox" })
                </td>
                <td>
                    <a href="#" class="easyui-linkbutton" id="btnQuery" data-options="iconCls:'icon-search'" style="width:80px">Search</a>
                </td>
            </tr>
        </table>
    </div>
    <div class="toolbar">@Html.Raw(ViewBag.ToolBar)</div>
</div>
<div data-options="region:'center',border:false">
    <table id="list" class="scroll" cellpadding="0" cellspacing="0"></table>
</div>
<div id="editframe"></div>
<div id="passwordframe"></div>

@section scripts{
    <script type="text/javascript" src="@Url.Content("~/Content/jiax/jiax.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            initQuery();
            initRefresh();
            initShowAdd();
            initShowUpdate();
            initDelete();
        });
    </script>
}

OAS/Views/Jiax/Select.cshtml
@model IEnumerable<OAS.Model.Jiax.tbl_jiax>
<select id="@ViewBag.ID" name="@ViewBag.Name" class="@ViewBag.ClassName" data-options="panelHeight:'auto'">
    <option value="">---</option>
    @if (Model != null)
    {
        foreach (var item in Model)
        {
            <option value="@item.jiaxid" @(item.jiaxid == ViewBag.Value ? "selected" : "")>@item.jiaxname</option>
        }
    }
</select>